# Generated by Django 2.2.1 on 2019-05-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
